version: "3.3"
services:
  ftp:
    image: delfer/alpine-ftp-server
    restart: always
    ports:
      - 21:21
      - 21000-21010:21000-21010
    volumes:
      - ./storage:/home/${FTP_USER}
    environment:
      - USERS=${FTP_USER}|${FTP_PASSWORD}|/home/${FTP_USER}